<?php

use Smartsupp\ChatGenerator;

if ($block->_getOption('active')) {
    $chat = new ChatGenerator($block->_getOption('chatId'));
    $chat->setPlatform("Magento " . $block->getMagentoVersion());

    $customerSession = $block->getCustomerSession();

    if ($customerSession !== null && $customerSession->isLoggedIn()) {
        $customer = $customerSession->getCustomer();
        $chat->setEmail($block->escapeHtml($customer->getEmail()));
        $chat->setName($block->escapeHtml($customer->getName()));
        $chat->setVariable('id', 'User ID', $block->escapeHtml($customer->getId()));
    }

    $chat->render(true);

    if ($optionalCode = $block->_getOption('optionalCode')) {
        echo '<script>' . /* @noEscape */ stripcslashes($optionalCode) . '</script>';
    }
}