<?php

use Smartsupp\ChatGenerator;

if ($block->_getOption('active')) {
	$chat = new ChatGenerator($block->_getOption('chatId'));
    $chat->setPlatform("Magento " . $block->getMagentoVersion());
	$chat->setEmail($block->_getOption('email'));
	$chat->render(true);
}

/**
 // @todo obtain information about visitor
 */

if ($optionalCode = $block->_getOption('optionalCode')) {
	echo '<script>' . stripcslashes($optionalCode) . '</script>';
}
