<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">

<div class="wrap" id="content">
	<?php if ($this->getActive()) { ?>
		<main role="main">
			<div id="third">
				<section class="top-bar">
					<div class="text-center">
						<img src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/logo.png') ?>" alt="smartsupp logo" />
					</div>
				</section>
				<section class="deactivate">
					<div class="row">
						<p class="bold">
							<span class="left"><?= $this->getEmail() ?: '' ?></span>
							<span class="right"><a class="js-action-disable" href="javascript: void(0);">Deactivate Chat</a></span>
						</p>
						<div class="clear"></div>
						<section class="intro">
                            <h4>
                                <strong class="green">Smartsupp’s chat box is now visible on your website.</strong> <br /><br />
                                Go to Smartsupp to chat with visitors, customize chat box design and access all features.
                            </h4>
                            <div class="intro--btn">
								<a href="https://dashboard.smartsupp.com?utm_source=Magento&utm_medium=integration&utm_campaign=link" target="_blank" class="js-register btn btn-primary btn-xl">Go to Smartsupp</a>
							</div>
							<p class="tiny text-center bigger-m">(This will open a new browser tab)</p>
						</section>
					</div>
				</section>
				<section>
					<div class="settings-container">
						<div class="section--header">
							<h3 class="no-margin bold">Advanced settings</h3>
							<p>Don't put the chat code here — this box is for (optional) advanced customizations via <a href="https://developers.smartsupp.com?utm_source=Magento&utm_medium=integration&utm_campaign=link" target="_blank">Smartsupp API</a></p>
						</div>
						<div class="section--body">
							<form action="" method="post" id="settingsForm" class="js-code-form form-horizontal" autocomplete="off">
								<div class="alerts">
									<?php if ($this->getMessage()) { ?>
										<div class="alert alert-success">
											<?= $this->getMessage() ?>
										</div>
									<?php } ?>
								</div>
								<div class="form-group">
									<div class="col-xs-12">
										<textarea name="code" id="textAreaSettings" cols="30" rows="10"><?= stripcslashes($this->getOptionalCode() ?: '') ?></textarea>
									</div>
								</div>
								<div class="form-group">
									<div class="col-xs-12">
										<div class="loader"></div>
										<button type="submit" class="btn btn-primary btn-lg" name="_submit">
											Save changes
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</section>
			</div>
		</main>
	<?php } else { ?>
		<main role="main" class="sections" id="home"<?php if ($this->getFormAction()) { ?> style="display: none;"<?php } ?>>
			<div id="first">
				<section class="top-bar">
					<div class="">
						<img src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/logo.png') ?>" alt="smartsupp logo" />
						<a href="javascript: void(0);" class="js-login btn btn-default">Connect existing account</a>
					</div>
				</section>
				<section class="intro">
					<div class="">
						<h1 class="lead">Free live chat with visitor recording</h1>
						<h3>Your customers are on your website right now. <br/>Chat with them and see what they do.</h3>
						<div class="intro--btn">
							<a href="javascript: void(0);" class="js-register btn btn-primary btn-xl">Create a free account</a>
						</div>
						<div class="intro--image">
							<img src="https://www.smartsupp.com/assets/images/dash/en.png" alt="intro" />
						</div>
					</div>
				</section>
				<section>
					<div class=" text-center">
						<div class="section--header">
							<h2>Enjoy unlimited agents and chats forever for free<br />or take advantage of premium packages with advanced features.</h2>
							<p><strong>See all features on </strong><a href="https://www.smartsupp.com?utm_source=Magento&utm_medium=integration&utm_campaign=link" target="_blank"> our website.</a></p>
						</div>
						<div class="section--body boxies">
							<div class="row">
								<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 box box-bubble">
									<p class="bold">Chat with visitors in real-time</p>
									<p class="tiny">Answering questions right away improves loyalty and helps you build closer relationships with your customers.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 box box-graph">
									<p class="bold">Increase online sales</p>
									<p class="tiny">Turn your visitors into customers.<br />Visitors who chat with you buy up to 5x more often - measurable in Google Analytics.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 box box-mouse">
									<p class="bold">Visitor screen recording</p>
									<p class="tiny">Watch visitor's behavior on your store.<br />You see his screen, mouse movement, clicks and what he filled into forms.</p>
								</div>
							</div>
						</div>
						<div class="section--header">
							<h2>Trusted by more than 55 000 companies</h2>
						</div>
						<div class="section--body">
							<div class="customers">
								<img class="partner" src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/skoda.png') ?>" alt="ŠKODA AUTO a.s." />
								<img class="partner" src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/gekko.png') ?>" alt="GEKKO Computer" />
								<img class="partner" src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/lememo.png') ?>" alt="Lememo" />
								<img class="partner" src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/conrad.png') ?>" alt="Conrad" />
							</div>
						</div>
					</div>
				</section>
			</div>
		</main>
		<main role="main" class="sections" id="connect"<?php if (!$this->getFormAction()) { ?> style="display: none;"<?php } ?>>
			<div id="second">
				<section class="top-bar">
					<div>
						<a href="javascript: void(0);" class="js-close-form">
							<img src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/logo.png') ?>" alt="smartsupp logo" />
							<a href="javascript: void(0);" class="btn btn-default" data-toggle-form data-multitext data-register="Connect existing account" data-login="Create a free account">
								<?= $this->getFormAction() === 'register' ? 'Connect existing account' : 'Create a free account' ?>
							</a>
						</a>
					</div>
				</section>
				<section id="signUp">
					<div class="text-center">
						<div class="form-container">
							<div class="section--header">
								<h1 class="lead" data-multitext data-login="Connect existing account" data-register="Create a free account">
									<?= $this->getFormAction() === 'login' ? 'Connect existing account' : 'Create a free account' ?>
								</h1>
							</div>
							<div class="section--body">
								<div class="form--inner">
									<form action="" method="post" id="signUpForm" class="form-horizontal<?= $this->getFormAction() ? (' js-' . $formAction . '-form') : '' ?>" data-toggle-class autocomplete="off">
										<div class="alerts">
											<?php if ($this->getMessage()) { ?>
												<div class="alert alert-danger js-clear">
													<?= $this->getMessage() ?>
												</div>
											<?php } ?>
										</div>
										<div class="form-group">
											<label class="visible-xs control-label col-xs-12" for="frm-signUp-form-email">E-mail</label>
											<div class="col-xs-12">
												<div class="input-group">
													<span class="input-group-addon hidden-xs" style="min-width: 150px;">E-mail</span>
													<input type="email" class="form-control input-lg" name="email" id="frm-signUp-form-email" required="" value="<?= $this->getEmail() ?: '' ?>">
												</div>
											</div>
										</div>
										<div class="form-group">
											<label class="visible-xs control-label col-xs-12" for="frm-signUp-form-password">Password</label>
											<div class="col-xs-12">
												<div class="input-group">
													<span class="input-group-addon hidden-xs" style="min-width: 150px;">Password</span>
													<input type="password" class="form-control input-lg" name="password" autocomplete="off" id="frm-signUp-form-password" required="">
												</div>
											</div>
										</div>
										<div class="form-group">
											<div class="col-xs-12 form-button">
												<div class="loader"></div>
												<button type="submit" class="btn btn-primary btn-lg btn-block" name="_submit" data-multitext data-login="Connect account" data-register="Sign up">
													<?= $this->getFormAction() === 'login' ? 'Connect account' : 'Sign up' ?>
												</button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
						<div class="section--header">
							<h2>Trusted by more than 55 000 companies</h2>
						</div>
						<div class="section--body">
							<div class="customers">
                                <img class="partner" src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/skoda.png') ?>" alt="ŠKODA AUTO a.s." />
                                <img class="partner" src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/gekko.png') ?>" alt="GEKKO Computer" />
                                <img class="partner" src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/lememo.png') ?>" alt="Lememo" />
                                <img class="partner" src="<?php echo $this->getViewFileUrl('Smartsupp_Smartsupp::images/conrad.png') ?>" alt="Conrad" />
							</div>
						</div>
					</div>
				</section>
			</div>
		</main>
	<?php } ?>
</div>